


[theme]
# Primary accent color for interactive elements.
primaryColor = "#ff6361"

# Background color for the main content area.
backgroundColor = "#00202e"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#ffa600"

# Color used for almost all text.
textColor = "#fff"